- hosts: vagrant
  user: vagrant
  tasks:
    -
      name: install ruby
      become: yes
      yum:
        name: 'https://github.com/feedforce/ruby-rpm/releases/download/2.6.0/ruby-2.6.0-1.el7.centos.x86_64.rpm'
        state: present
